#! /usr/bin/env perl
#
# A simple DICOM dumper
#
# Copyright Andrew Janke - a.janke@gmail.com
# Permission to use, copy, modify, and distribute this software and its
# documentation for any purpose and without fee is hereby granted,
# provided that the above copyright notice appear in all copies.  The
# author makes no representations about the suitability of this software
# for any purpose.  It is provided "as is" without express or implied warranty.


#use strict;
use warnings "all";
use Getopt::Long;
use Pod::Usage;
use File::Basename;
use Cwd;

use DICOM;
use DICOM::Fields;
use DICOM::Element;

# until I get organised and do this properly
my $PACKAGE = &basename($0);
my $VERSION = '1.0.0';
my $PACKAGE_BUGREPORT = '"Andrew Janke" <a.janke@gmail.com>';

my($me, %opt, @command, $script);

$me = &basename($0);
%opt = (verbose => 0,
        fake => 0,
        man => 0,
        help => 0,
        );

# Get the history string
chomp($history = `date`);
$history .= '>>>> ' . join(' ', $me, @ARGV) . "\n";

# Check arguments
&GetOptions(
   'help|?' => \$opt{'help'},
   'man' => \$opt{'man'},
   'v|verbose' => \$opt{'verbose'},
   'version' => sub { &print_version_info },
   'f|fake' => \$opt{'fake'},
   ) or pod2usage(-verbose => 1) && exit;
   
# handle -man, -help or missing args
pod2usage(-verbose => 1) if $opt{help};
pod2usage(-exitstatus => 0, -verbose => 2) if $opt{man};
pod2usage(-verbose => 0) && exit if ($#ARGV != 0);

# get the input file and fill er up.
$infile = $ARGV[0];

my $d = DICOM->new();
$d->fill($infile);

print "CONTENTS ($infile)\n";
#$d->printContents();

$d->write("out.dcm");

sub do_cmd { 
   print STDOUT "@_\n" if $opt{verbose};
   if(!$opt{fake}){
      system(@_) == 0 or die;
      }
   }

sub print_version_info {
   print STDOUT "\n$PACKAGE version $VERSION\n".
                "Comments to $PACKAGE_BUGREPORT\n\n";
   exit;
   }


__END__

=head1 NAME

B<mnc2dcm> - simple MINC to Dicom converter

=head1 SYNOPSIS

B<mnc2dcm> [options] in.mnc out_base

mnc2dcm should work to convert 3D MINC volumes to Dicom "format". By
Dicom format I mean as much to spec as possible. Mind you this in
NO WAY means that you will be able to re-import these images into some
scanner interface as most of these have their own addittions to Dicom
that are not always that compatible with each other. So yes your images
might be importable into such scanner interfaces but also might not.

They should howver be easily readable with Dicom viewers such as Osirix,
Sante Dicom Viewer and ImageJ (three of the viewers on which the output
of mnc2dcm has been tested).

   $ mnc2dcm <in.mnc> <outdir>

=head1 DESCRIPTION

B<mnc2dcm> is a bit of a hack really though as all it does is call ...

 eg:
    $ mnc2dcm <in.mnc> <outdir>

Problems or comments should not be sent to: a.janke@gmail.com he really
is not all that interested in maintaining things that pertain to DICOM
as it seems to be a constantly moving target. But hey you can
still email and you might just get lucky, he might be having a good day.

=head1 OPTIONS

=over 4

=item B<-v>, B<--verbose>

Be noisy when doing things (most importantly this will echo the resulting script to the terminal)

=item B<--version>

Print version number and exit

=item B<-h>, B<--help>

Dump some quick help output

=item B<--man>

Dump a man page

=item B<-f>, B<--fake>

Do a dry run. This is usually only useful if combined with --verbose so that you can see what is going on.

=back

=head1 SEE ALSO

dconvert(1)

=head1 AUTHOR

Andrew Janke - a.janke@gmail.com

=cut
